# Generated by Django 4.1.7 on 2023-02-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_alter_uid_uid_arr'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_chek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('kod', models.CharField(max_length=100)),
            ],
        ),
    ]
